# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pan-session-viewer-ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 717)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/logo.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 341, 221))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 321, 120))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.ip_address = QtWidgets.QLineEdit(self.layoutWidget)
        self.ip_address.setObjectName("ip_address")
        self.gridLayout.addWidget(self.ip_address, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(self.layoutWidget)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.button_connect = QtWidgets.QPushButton(self.layoutWidget)
        self.button_connect.setAutoDefault(True)
        self.button_connect.setObjectName("button_connect")
        self.gridLayout.addWidget(self.button_connect, 3, 1, 1, 1)
        self.username = QtWidgets.QLineEdit(self.layoutWidget)
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(360, 10, 731, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.button_search = QtWidgets.QPushButton(self.groupBox_2)
        self.button_search.setEnabled(False)
        self.button_search.setGeometry(QtCore.QRect(220, 190, 247, 23))
        self.button_search.setAutoDefault(True)
        self.button_search.setObjectName("button_search")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 20, 331, 157))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.src_ip = QtWidgets.QLineEdit(self.layoutWidget1)
        self.src_ip.setObjectName("src_ip")
        self.gridLayout_2.addWidget(self.src_ip, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.dst_ip = QtWidgets.QLineEdit(self.layoutWidget1)
        self.dst_ip.setObjectName("dst_ip")
        self.gridLayout_2.addWidget(self.dst_ip, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.cbo_src_zone = QtWidgets.QComboBox(self.layoutWidget1)
        self.cbo_src_zone.setObjectName("cbo_src_zone")
        self.gridLayout_2.addWidget(self.cbo_src_zone, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
        self.cbo_src_intf = QtWidgets.QComboBox(self.layoutWidget1)
        self.cbo_src_intf.setObjectName("cbo_src_intf")
        self.gridLayout_2.addWidget(self.cbo_src_intf, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.appid = QtWidgets.QLineEdit(self.layoutWidget1)
        self.appid.setObjectName("appid")
        self.gridLayout_2.addWidget(self.appid, 4, 1, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(350, 21, 371, 157))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.src_port = QtWidgets.QLineEdit(self.layoutWidget2)
        self.src_port.setObjectName("src_port")
        self.gridLayout_3.addWidget(self.src_port, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 2)
        self.dst_port = QtWidgets.QLineEdit(self.layoutWidget2)
        self.dst_port.setObjectName("dst_port")
        self.gridLayout_3.addWidget(self.dst_port, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 2)
        self.cbo_dst_zone = QtWidgets.QComboBox(self.layoutWidget2)
        self.cbo_dst_zone.setObjectName("cbo_dst_zone")
        self.gridLayout_3.addWidget(self.cbo_dst_zone, 2, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 0, 1, 2)
        self.cbo_dst_intf = QtWidgets.QComboBox(self.layoutWidget2)
        self.cbo_dst_intf.setObjectName("cbo_dst_intf")
        self.gridLayout_3.addWidget(self.cbo_dst_intf, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 2)
        self.src_user = QtWidgets.QLineEdit(self.layoutWidget2)
        self.src_user.setObjectName("src_user")
        self.gridLayout_3.addWidget(self.src_user, 4, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 4, 0, 1, 2)
        self.output_area = QtWidgets.QTextBrowser(self.centralwidget)
        self.output_area.setGeometry(QtCore.QRect(10, 270, 1081, 101))
        self.output_area.setObjectName("output_area")
        self.button_quit = QtWidgets.QPushButton(self.centralwidget)
        self.button_quit.setGeometry(QtCore.QRect(1010, 670, 75, 23))
        self.button_quit.setAutoDefault(True)
        self.button_quit.setObjectName("button_quit")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(10, 240, 921, 16))
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.button_clear_log = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear_log.setGeometry(QtCore.QRect(950, 240, 131, 23))
        self.button_clear_log.setAutoDefault(True)
        self.button_clear_log.setObjectName("button_clear_log")
        self.button_clear_session_wnd = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear_session_wnd.setGeometry(QtCore.QRect(810, 670, 161, 23))
        self.button_clear_session_wnd.setAutoDefault(True)
        self.button_clear_session_wnd.setObjectName("button_clear_session_wnd")
        self.tableSessions = QtWidgets.QTableWidget(self.centralwidget)
        self.tableSessions.setGeometry(QtCore.QRect(10, 420, 1081, 241))
        self.tableSessions.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableSessions.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableSessions.setObjectName("tableSessions")
        self.tableSessions.setColumnCount(0)
        self.tableSessions.setRowCount(0)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 400, 341, 16))
        self.label_11.setObjectName("label_11")
        self.chkbox_refresh_search = QtWidgets.QCheckBox(self.centralwidget)
        self.chkbox_refresh_search.setGeometry(QtCore.QRect(890, 390, 201, 20))
        self.chkbox_refresh_search.setObjectName("chkbox_refresh_search")
        self.btn_refresh_existing = QtWidgets.QPushButton(self.centralwidget)
        self.btn_refresh_existing.setGeometry(QtCore.QRect(630, 670, 171, 23))
        self.btn_refresh_existing.setAutoDefault(True)
        self.btn_refresh_existing.setObjectName("btn_refresh_existing")
        self.lbl_sessions_tracked = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sessions_tracked.setGeometry(QtCore.QRect(10, 660, 141, 16))
        self.lbl_sessions_tracked.setObjectName("lbl_sessions_tracked")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.ip_address, self.username)
        MainWindow.setTabOrder(self.username, self.password)
        MainWindow.setTabOrder(self.password, self.button_connect)
        MainWindow.setTabOrder(self.button_connect, self.src_ip)
        MainWindow.setTabOrder(self.src_ip, self.src_port)
        MainWindow.setTabOrder(self.src_port, self.dst_ip)
        MainWindow.setTabOrder(self.dst_ip, self.dst_port)
        MainWindow.setTabOrder(self.dst_port, self.cbo_src_zone)
        MainWindow.setTabOrder(self.cbo_src_zone, self.cbo_dst_zone)
        MainWindow.setTabOrder(self.cbo_dst_zone, self.cbo_src_intf)
        MainWindow.setTabOrder(self.cbo_src_intf, self.cbo_dst_intf)
        MainWindow.setTabOrder(self.cbo_dst_intf, self.appid)
        MainWindow.setTabOrder(self.appid, self.src_user)
        MainWindow.setTabOrder(self.src_user, self.button_search)
        MainWindow.setTabOrder(self.button_search, self.output_area)
        MainWindow.setTabOrder(self.output_area, self.button_clear_log)
        MainWindow.setTabOrder(self.button_clear_log, self.tableSessions)
        MainWindow.setTabOrder(self.tableSessions, self.chkbox_refresh_search)
        MainWindow.setTabOrder(self.chkbox_refresh_search, self.btn_refresh_existing)
        MainWindow.setTabOrder(self.btn_refresh_existing, self.button_clear_session_wnd)
        MainWindow.setTabOrder(self.button_clear_session_wnd, self.button_quit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pan-session-viewer"))
        self.groupBox.setTitle(_translate("MainWindow", "Firewall Admin Login"))
        self.label.setText(_translate("MainWindow", "IP/Hostname:"))
        self.label_2.setText(_translate("MainWindow", "Username:"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.button_connect.setText(_translate("MainWindow", "Connect"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Search Criteria"))
        self.button_search.setText(_translate("MainWindow", "Search Sessions"))
        self.label_4.setText(_translate("MainWindow", "Source IP:"))
        self.label_7.setText(_translate("MainWindow", "Destination IP:"))
        self.label_9.setText(_translate("MainWindow", "Source Zone:"))
        self.label_13.setText(_translate("MainWindow", "Source Interface:"))
        self.label_10.setText(_translate("MainWindow", "App-ID:"))
        self.label_6.setText(_translate("MainWindow", "Destination Port:"))
        self.label_8.setText(_translate("MainWindow", "Destination Zone:"))
        self.label_12.setText(_translate("MainWindow", "Destination Interface:"))
        self.label_5.setText(_translate("MainWindow", "Source Port:"))
        self.label_14.setText(_translate("MainWindow", "Source User"))
        self.button_quit.setText(_translate("MainWindow", "Quit"))
        self.button_clear_log.setText(_translate("MainWindow", "Clear Log Window"))
        self.button_clear_session_wnd.setText(_translate("MainWindow", "Clear Session Window"))
        self.label_11.setText(_translate("MainWindow", "Double-Click Session to View Detailed Information"))
        self.chkbox_refresh_search.setText(_translate("MainWindow", "Auto-Refresh Session Search"))
        self.btn_refresh_existing.setText(_translate("MainWindow", "Refresh Existing Sessions"))
        self.lbl_sessions_tracked.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of sessions tracked.  Includes expired sessions and sessions from previous searches.</p><p>Click \'Clear Session Window\' to start over</p></body></html>"))
        self.lbl_sessions_tracked.setText(_translate("MainWindow", "Sessions Tracked: 0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

