# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'session-detail.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SessionDetail(object):
    def setupUi(self, SessionDetail):
        SessionDetail.setObjectName("SessionDetail")
        SessionDetail.resize(738, 624)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SessionDetail.sizePolicy().hasHeightForWidth())
        SessionDetail.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/logo.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SessionDetail.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(SessionDetail)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1300, 610, 47, 13))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 50, 331, 221))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 311, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.lbl_c2s_srcip = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_c2s_srcip.sizePolicy().hasHeightForWidth())
        self.lbl_c2s_srcip.setSizePolicy(sizePolicy)
        self.lbl_c2s_srcip.setText("")
        self.lbl_c2s_srcip.setObjectName("lbl_c2s_srcip")
        self.gridLayout_2.addWidget(self.lbl_c2s_srcip, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.lbl_c2s_dstip = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_c2s_dstip.sizePolicy().hasHeightForWidth())
        self.lbl_c2s_dstip.setSizePolicy(sizePolicy)
        self.lbl_c2s_dstip.setText("")
        self.lbl_c2s_dstip.setObjectName("lbl_c2s_dstip")
        self.gridLayout_2.addWidget(self.lbl_c2s_dstip, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.lbl_c2s_proto = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_c2s_proto.sizePolicy().hasHeightForWidth())
        self.lbl_c2s_proto.setSizePolicy(sizePolicy)
        self.lbl_c2s_proto.setText("")
        self.lbl_c2s_proto.setObjectName("lbl_c2s_proto")
        self.gridLayout_2.addWidget(self.lbl_c2s_proto, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.lbl_c2s_srcport = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_c2s_srcport.sizePolicy().hasHeightForWidth())
        self.lbl_c2s_srcport.setSizePolicy(sizePolicy)
        self.lbl_c2s_srcport.setText("")
        self.lbl_c2s_srcport.setObjectName("lbl_c2s_srcport")
        self.gridLayout_2.addWidget(self.lbl_c2s_srcport, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.lbl_c2s_dstport = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_c2s_dstport.sizePolicy().hasHeightForWidth())
        self.lbl_c2s_dstport.setSizePolicy(sizePolicy)
        self.lbl_c2s_dstport.setText("")
        self.lbl_c2s_dstport.setObjectName("lbl_c2s_dstport")
        self.gridLayout_2.addWidget(self.lbl_c2s_dstport, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 5, 0, 1, 1)
        self.lbl_c2s_state = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_c2s_state.sizePolicy().hasHeightForWidth())
        self.lbl_c2s_state.setSizePolicy(sizePolicy)
        self.lbl_c2s_state.setText("")
        self.lbl_c2s_state.setObjectName("lbl_c2s_state")
        self.gridLayout_2.addWidget(self.lbl_c2s_state, 5, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 6, 0, 1, 1)
        self.lbl_c2s_type = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_c2s_type.sizePolicy().hasHeightForWidth())
        self.lbl_c2s_type.setSizePolicy(sizePolicy)
        self.lbl_c2s_type.setText("")
        self.lbl_c2s_type.setObjectName("lbl_c2s_type")
        self.gridLayout_2.addWidget(self.lbl_c2s_type, 6, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 7, 0, 1, 1)
        self.lbl_c2s_srcuser = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_c2s_srcuser.sizePolicy().hasHeightForWidth())
        self.lbl_c2s_srcuser.setSizePolicy(sizePolicy)
        self.lbl_c2s_srcuser.setText("")
        self.lbl_c2s_srcuser.setObjectName("lbl_c2s_srcuser")
        self.gridLayout_2.addWidget(self.lbl_c2s_srcuser, 7, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 8, 0, 1, 1)
        self.lbl_c2s_dstuser = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_c2s_dstuser.sizePolicy().hasHeightForWidth())
        self.lbl_c2s_dstuser.setSizePolicy(sizePolicy)
        self.lbl_c2s_dstuser.setText("")
        self.lbl_c2s_dstuser.setObjectName("lbl_c2s_dstuser")
        self.gridLayout_2.addWidget(self.lbl_c2s_dstuser, 8, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 50, 331, 221))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 311, 191))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 0, 0, 1, 1)
        self.lbl_s2c_srcip = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_s2c_srcip.sizePolicy().hasHeightForWidth())
        self.lbl_s2c_srcip.setSizePolicy(sizePolicy)
        self.lbl_s2c_srcip.setText("")
        self.lbl_s2c_srcip.setObjectName("lbl_s2c_srcip")
        self.gridLayout_3.addWidget(self.lbl_s2c_srcip, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 1, 0, 1, 1)
        self.lbl_s2c_dstip = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_s2c_dstip.sizePolicy().hasHeightForWidth())
        self.lbl_s2c_dstip.setSizePolicy(sizePolicy)
        self.lbl_s2c_dstip.setText("")
        self.lbl_s2c_dstip.setObjectName("lbl_s2c_dstip")
        self.gridLayout_3.addWidget(self.lbl_s2c_dstip, 1, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 2, 0, 1, 1)
        self.lbl_s2c_proto = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_s2c_proto.sizePolicy().hasHeightForWidth())
        self.lbl_s2c_proto.setSizePolicy(sizePolicy)
        self.lbl_s2c_proto.setText("")
        self.lbl_s2c_proto.setObjectName("lbl_s2c_proto")
        self.gridLayout_3.addWidget(self.lbl_s2c_proto, 2, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 3, 0, 1, 1)
        self.lbl_s2c_srcport = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_s2c_srcport.sizePolicy().hasHeightForWidth())
        self.lbl_s2c_srcport.setSizePolicy(sizePolicy)
        self.lbl_s2c_srcport.setText("")
        self.lbl_s2c_srcport.setObjectName("lbl_s2c_srcport")
        self.gridLayout_3.addWidget(self.lbl_s2c_srcport, 3, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 4, 0, 1, 1)
        self.lbl_s2c_dstport = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_s2c_dstport.sizePolicy().hasHeightForWidth())
        self.lbl_s2c_dstport.setSizePolicy(sizePolicy)
        self.lbl_s2c_dstport.setText("")
        self.lbl_s2c_dstport.setObjectName("lbl_s2c_dstport")
        self.gridLayout_3.addWidget(self.lbl_s2c_dstport, 4, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 5, 0, 1, 1)
        self.lbl_s2c_state = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_s2c_state.sizePolicy().hasHeightForWidth())
        self.lbl_s2c_state.setSizePolicy(sizePolicy)
        self.lbl_s2c_state.setText("")
        self.lbl_s2c_state.setObjectName("lbl_s2c_state")
        self.gridLayout_3.addWidget(self.lbl_s2c_state, 5, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 6, 0, 1, 1)
        self.lbl_s2c_type = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_s2c_type.sizePolicy().hasHeightForWidth())
        self.lbl_s2c_type.setSizePolicy(sizePolicy)
        self.lbl_s2c_type.setText("")
        self.lbl_s2c_type.setObjectName("lbl_s2c_type")
        self.gridLayout_3.addWidget(self.lbl_s2c_type, 6, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 7, 0, 1, 1)
        self.lbl_s2c_srcuser = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_s2c_srcuser.sizePolicy().hasHeightForWidth())
        self.lbl_s2c_srcuser.setSizePolicy(sizePolicy)
        self.lbl_s2c_srcuser.setText("")
        self.lbl_s2c_srcuser.setObjectName("lbl_s2c_srcuser")
        self.gridLayout_3.addWidget(self.lbl_s2c_srcuser, 7, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 8, 0, 1, 1)
        self.lbl_s2c_dstuser = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_s2c_dstuser.sizePolicy().hasHeightForWidth())
        self.lbl_s2c_dstuser.setSizePolicy(sizePolicy)
        self.lbl_s2c_dstuser.setText("")
        self.lbl_s2c_dstuser.setObjectName("lbl_s2c_dstuser")
        self.gridLayout_3.addWidget(self.lbl_s2c_dstuser, 8, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 290, 701, 261))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 21, 311, 224))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 0, 0, 1, 1)
        self.lbl_slot = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_slot.sizePolicy().hasHeightForWidth())
        self.lbl_slot.setSizePolicy(sizePolicy)
        self.lbl_slot.setText("")
        self.lbl_slot.setObjectName("lbl_slot")
        self.gridLayout_4.addWidget(self.lbl_slot, 0, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 1, 0, 1, 1)
        self.lbl_dp = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_dp.sizePolicy().hasHeightForWidth())
        self.lbl_dp.setSizePolicy(sizePolicy)
        self.lbl_dp.setText("")
        self.lbl_dp.setObjectName("lbl_dp")
        self.gridLayout_4.addWidget(self.lbl_dp, 1, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_36.setObjectName("label_36")
        self.gridLayout_4.addWidget(self.label_36, 2, 0, 1, 1)
        self.lbl_index = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_index.sizePolicy().hasHeightForWidth())
        self.lbl_index.setSizePolicy(sizePolicy)
        self.lbl_index.setText("")
        self.lbl_index.setObjectName("lbl_index")
        self.gridLayout_4.addWidget(self.lbl_index, 2, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_38.setObjectName("label_38")
        self.gridLayout_4.addWidget(self.label_38, 3, 0, 1, 1)
        self.lbl_starttime = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_starttime.sizePolicy().hasHeightForWidth())
        self.lbl_starttime.setSizePolicy(sizePolicy)
        self.lbl_starttime.setText("")
        self.lbl_starttime.setObjectName("lbl_starttime")
        self.gridLayout_4.addWidget(self.lbl_starttime, 3, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 4, 0, 1, 1)
        self.lbl_timeout = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_timeout.sizePolicy().hasHeightForWidth())
        self.lbl_timeout.setSizePolicy(sizePolicy)
        self.lbl_timeout.setText("")
        self.lbl_timeout.setObjectName("lbl_timeout")
        self.gridLayout_4.addWidget(self.lbl_timeout, 4, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_42.setObjectName("label_42")
        self.gridLayout_4.addWidget(self.label_42, 5, 0, 1, 1)
        self.lbl_ttl = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_ttl.sizePolicy().hasHeightForWidth())
        self.lbl_ttl.setSizePolicy(sizePolicy)
        self.lbl_ttl.setText("")
        self.lbl_ttl.setObjectName("lbl_ttl")
        self.gridLayout_4.addWidget(self.lbl_ttl, 5, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_44.setObjectName("label_44")
        self.gridLayout_4.addWidget(self.label_44, 6, 0, 1, 1)
        self.lbl_bytes_c2s = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_bytes_c2s.sizePolicy().hasHeightForWidth())
        self.lbl_bytes_c2s.setSizePolicy(sizePolicy)
        self.lbl_bytes_c2s.setText("")
        self.lbl_bytes_c2s.setObjectName("lbl_bytes_c2s")
        self.gridLayout_4.addWidget(self.lbl_bytes_c2s, 6, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_45.setObjectName("label_45")
        self.gridLayout_4.addWidget(self.label_45, 7, 0, 1, 1)
        self.lbl_bytes_s2c = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_bytes_s2c.sizePolicy().hasHeightForWidth())
        self.lbl_bytes_s2c.setSizePolicy(sizePolicy)
        self.lbl_bytes_s2c.setText("")
        self.lbl_bytes_s2c.setObjectName("lbl_bytes_s2c")
        self.gridLayout_4.addWidget(self.lbl_bytes_s2c, 7, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_47.setObjectName("label_47")
        self.gridLayout_4.addWidget(self.label_47, 8, 0, 1, 1)
        self.lbl_pkts_c2s = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_pkts_c2s.sizePolicy().hasHeightForWidth())
        self.lbl_pkts_c2s.setSizePolicy(sizePolicy)
        self.lbl_pkts_c2s.setText("")
        self.lbl_pkts_c2s.setObjectName("lbl_pkts_c2s")
        self.gridLayout_4.addWidget(self.lbl_pkts_c2s, 8, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_49.setObjectName("label_49")
        self.gridLayout_4.addWidget(self.label_49, 9, 0, 1, 1)
        self.lbl_pkts_s2c = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_pkts_s2c.sizePolicy().hasHeightForWidth())
        self.lbl_pkts_s2c.setSizePolicy(sizePolicy)
        self.lbl_pkts_s2c.setText("")
        self.lbl_pkts_s2c.setObjectName("lbl_pkts_s2c")
        self.gridLayout_4.addWidget(self.lbl_pkts_s2c, 9, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_51.setObjectName("label_51")
        self.gridLayout_4.addWidget(self.label_51, 10, 0, 1, 1)
        self.lbl_vsys = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_vsys.sizePolicy().hasHeightForWidth())
        self.lbl_vsys.setSizePolicy(sizePolicy)
        self.lbl_vsys.setText("")
        self.lbl_vsys.setObjectName("lbl_vsys")
        self.gridLayout_4.addWidget(self.lbl_vsys, 10, 1, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_76.setObjectName("label_76")
        self.gridLayout_4.addWidget(self.label_76, 11, 0, 1, 1)
        self.lbl_ingress_intf = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_ingress_intf.sizePolicy().hasHeightForWidth())
        self.lbl_ingress_intf.setSizePolicy(sizePolicy)
        self.lbl_ingress_intf.setText("")
        self.lbl_ingress_intf.setObjectName("lbl_ingress_intf")
        self.gridLayout_4.addWidget(self.lbl_ingress_intf, 11, 1, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(380, 21, 311, 224))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_53 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_53.setObjectName("label_53")
        self.gridLayout_5.addWidget(self.label_53, 0, 0, 1, 1)
        self.lbl_application = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_application.sizePolicy().hasHeightForWidth())
        self.lbl_application.setSizePolicy(sizePolicy)
        self.lbl_application.setText("")
        self.lbl_application.setObjectName("lbl_application")
        self.gridLayout_5.addWidget(self.lbl_application, 0, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_55.setObjectName("label_55")
        self.gridLayout_5.addWidget(self.label_55, 1, 0, 1, 1)
        self.lbl_rule = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_rule.sizePolicy().hasHeightForWidth())
        self.lbl_rule.setSizePolicy(sizePolicy)
        self.lbl_rule.setText("")
        self.lbl_rule.setObjectName("lbl_rule")
        self.gridLayout_5.addWidget(self.lbl_rule, 1, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_57.setObjectName("label_57")
        self.gridLayout_5.addWidget(self.label_57, 2, 0, 1, 1)
        self.lbl_logend = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_logend.sizePolicy().hasHeightForWidth())
        self.lbl_logend.setSizePolicy(sizePolicy)
        self.lbl_logend.setText("")
        self.lbl_logend.setObjectName("lbl_logend")
        self.gridLayout_5.addWidget(self.lbl_logend, 2, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_59.setObjectName("label_59")
        self.gridLayout_5.addWidget(self.label_59, 3, 0, 1, 1)
        self.lbl_ager = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_ager.sizePolicy().hasHeightForWidth())
        self.lbl_ager.setSizePolicy(sizePolicy)
        self.lbl_ager.setText("")
        self.lbl_ager.setObjectName("lbl_ager")
        self.gridLayout_5.addWidget(self.lbl_ager, 3, 1, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_61.setObjectName("label_61")
        self.gridLayout_5.addWidget(self.label_61, 4, 0, 1, 1)
        self.lbl_ha_update = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_ha_update.sizePolicy().hasHeightForWidth())
        self.lbl_ha_update.setSizePolicy(sizePolicy)
        self.lbl_ha_update.setText("")
        self.lbl_ha_update.setObjectName("lbl_ha_update")
        self.gridLayout_5.addWidget(self.lbl_ha_update, 4, 1, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_63.setObjectName("label_63")
        self.gridLayout_5.addWidget(self.label_63, 5, 0, 1, 1)
        self.lbl_layer7 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_layer7.sizePolicy().hasHeightForWidth())
        self.lbl_layer7.setSizePolicy(sizePolicy)
        self.lbl_layer7.setText("")
        self.lbl_layer7.setObjectName("lbl_layer7")
        self.gridLayout_5.addWidget(self.lbl_layer7, 5, 1, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_65.setObjectName("label_65")
        self.gridLayout_5.addWidget(self.label_65, 6, 0, 1, 1)
        self.lbl_url_filtering = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_url_filtering.sizePolicy().hasHeightForWidth())
        self.lbl_url_filtering.setSizePolicy(sizePolicy)
        self.lbl_url_filtering.setText("")
        self.lbl_url_filtering.setObjectName("lbl_url_filtering")
        self.gridLayout_5.addWidget(self.lbl_url_filtering, 6, 1, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_67.setObjectName("label_67")
        self.gridLayout_5.addWidget(self.label_67, 7, 0, 1, 1)
        self.lbl_syncookies = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_syncookies.sizePolicy().hasHeightForWidth())
        self.lbl_syncookies.setSizePolicy(sizePolicy)
        self.lbl_syncookies.setText("")
        self.lbl_syncookies.setObjectName("lbl_syncookies")
        self.gridLayout_5.addWidget(self.lbl_syncookies, 7, 1, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_69.setObjectName("label_69")
        self.gridLayout_5.addWidget(self.label_69, 8, 0, 1, 1)
        self.lbl_term_host = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_term_host.sizePolicy().hasHeightForWidth())
        self.lbl_term_host.setSizePolicy(sizePolicy)
        self.lbl_term_host.setText("")
        self.lbl_term_host.setObjectName("lbl_term_host")
        self.gridLayout_5.addWidget(self.lbl_term_host, 8, 1, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_71.setObjectName("label_71")
        self.gridLayout_5.addWidget(self.label_71, 9, 0, 1, 1)
        self.lbl_tunnel = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_tunnel.sizePolicy().hasHeightForWidth())
        self.lbl_tunnel.setSizePolicy(sizePolicy)
        self.lbl_tunnel.setText("")
        self.lbl_tunnel.setObjectName("lbl_tunnel")
        self.gridLayout_5.addWidget(self.lbl_tunnel, 9, 1, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_73.setObjectName("label_73")
        self.gridLayout_5.addWidget(self.label_73, 10, 0, 1, 1)
        self.lbl_cp = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_cp.sizePolicy().hasHeightForWidth())
        self.lbl_cp.setSizePolicy(sizePolicy)
        self.lbl_cp.setText("")
        self.lbl_cp.setObjectName("lbl_cp")
        self.gridLayout_5.addWidget(self.lbl_cp, 10, 1, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_78.setObjectName("label_78")
        self.gridLayout_5.addWidget(self.label_78, 11, 0, 1, 1)
        self.lbl_egress_intf = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_egress_intf.sizePolicy().hasHeightForWidth())
        self.lbl_egress_intf.setSizePolicy(sizePolicy)
        self.lbl_egress_intf.setText("")
        self.lbl_egress_intf.setObjectName("lbl_egress_intf")
        self.gridLayout_5.addWidget(self.lbl_egress_intf, 11, 1, 1, 1)
        self.btn_refresh = QtWidgets.QPushButton(self.centralwidget)
        self.btn_refresh.setGeometry(QtCore.QRect(330, 580, 75, 23))
        self.btn_refresh.setObjectName("btn_refresh")
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 10, 201, 16))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lbl_session_id = QtWidgets.QLabel(self.layoutWidget4)
        self.lbl_session_id.setText("")
        self.lbl_session_id.setObjectName("lbl_session_id")
        self.gridLayout.addWidget(self.lbl_session_id, 0, 1, 1, 1)
        self.layoutWidget5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(30, 580, 291, 16))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_77 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_77.setObjectName("label_77")
        self.gridLayout_6.addWidget(self.label_77, 0, 0, 1, 1)
        self.lbl_refreshtime = QtWidgets.QLabel(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_refreshtime.sizePolicy().hasHeightForWidth())
        self.lbl_refreshtime.setSizePolicy(sizePolicy)
        self.lbl_refreshtime.setText("")
        self.lbl_refreshtime.setObjectName("lbl_refreshtime")
        self.gridLayout_6.addWidget(self.lbl_refreshtime, 0, 1, 1, 1)
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(420, 580, 75, 23))
        self.btn_close.setObjectName("btn_close")
        SessionDetail.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SessionDetail)
        self.statusbar.setObjectName("statusbar")
        SessionDetail.setStatusBar(self.statusbar)

        self.retranslateUi(SessionDetail)
        QtCore.QMetaObject.connectSlotsByName(SessionDetail)

    def retranslateUi(self, SessionDetail):
        _translate = QtCore.QCoreApplication.translate
        SessionDetail.setWindowTitle(_translate("SessionDetail", "pan-session-viewer Session Detail"))
        self.label.setText(_translate("SessionDetail", "TextLabel"))
        self.groupBox.setTitle(_translate("SessionDetail", "Client to Server (c2s) flow"))
        self.label_4.setText(_translate("SessionDetail", "Source:"))
        self.label_5.setText(_translate("SessionDetail", "Destination:"))
        self.label_6.setText(_translate("SessionDetail", "Protocol:"))
        self.label_7.setText(_translate("SessionDetail", "Src Port:"))
        self.label_8.setText(_translate("SessionDetail", "Dst Port:"))
        self.label_9.setText(_translate("SessionDetail", "State:"))
        self.label_10.setText(_translate("SessionDetail", "Type:"))
        self.label_11.setText(_translate("SessionDetail", "Src User:"))
        self.label_12.setText(_translate("SessionDetail", "Dst user:"))
        self.groupBox_2.setTitle(_translate("SessionDetail", "Server to Client (s2c) flow"))
        self.label_22.setText(_translate("SessionDetail", "Source:"))
        self.label_23.setText(_translate("SessionDetail", "Destination:"))
        self.label_24.setText(_translate("SessionDetail", "Protocol:"))
        self.label_25.setText(_translate("SessionDetail", "Src Port:"))
        self.label_26.setText(_translate("SessionDetail", "Dst Port:"))
        self.label_27.setText(_translate("SessionDetail", "State:"))
        self.label_28.setText(_translate("SessionDetail", "Type:"))
        self.label_29.setText(_translate("SessionDetail", "Src User:"))
        self.label_30.setText(_translate("SessionDetail", "Dst user:"))
        self.groupBox_3.setTitle(_translate("SessionDetail", "Additional Details"))
        self.label_31.setText(_translate("SessionDetail", "Slot:"))
        self.label_34.setText(_translate("SessionDetail", "DP:"))
        self.label_36.setText(_translate("SessionDetail", "Index (Local):"))
        self.label_38.setText(_translate("SessionDetail", "Start Time:"))
        self.label_40.setText(_translate("SessionDetail", "Timeout:"))
        self.label_42.setText(_translate("SessionDetail", "Time To Live:"))
        self.label_44.setText(_translate("SessionDetail", "Total Byte Count (c2s):"))
        self.label_45.setText(_translate("SessionDetail", "Total Byte Count (s2c):"))
        self.label_47.setText(_translate("SessionDetail", "layer7 Packet Count (c2s):"))
        self.label_49.setText(_translate("SessionDetail", "layer7 Packet Count (s2c):"))
        self.label_51.setText(_translate("SessionDetail", "vsys:"))
        self.label_76.setText(_translate("SessionDetail", "Ingress Interface:"))
        self.label_53.setText(_translate("SessionDetail", "Application:"))
        self.label_55.setText(_translate("SessionDetail", "Rule:"))
        self.label_57.setText(_translate("SessionDetail", "Session Logged At End?"))
        self.label_59.setText(_translate("SessionDetail", "Session in Session Ager?"))
        self.label_61.setText(_translate("SessionDetail", "Session updated by HA Peer:"))
        self.label_63.setText(_translate("SessionDetail", "layer7 Processing:"))
        self.label_65.setText(_translate("SessionDetail", "URL Filtering Enabled?"))
        self.label_67.setText(_translate("SessionDetail", "Session via syn-cookies?"))
        self.label_69.setText(_translate("SessionDetail", "session terminated on host?"))
        self.label_71.setText(_translate("SessionDetail", "Session traverses tunnel?"))
        self.label_73.setText(_translate("SessionDetail", "Captive Portal Session?"))
        self.label_78.setText(_translate("SessionDetail", "Egress Interface:"))
        self.btn_refresh.setText(_translate("SessionDetail", "Refresh"))
        self.label_2.setText(_translate("SessionDetail", "Details for Session ID:"))
        self.label_77.setText(_translate("SessionDetail", "Last Refreshed:"))
        self.btn_close.setText(_translate("SessionDetail", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SessionDetail = QtWidgets.QMainWindow()
    ui = Ui_SessionDetail()
    ui.setupUi(SessionDetail)
    SessionDetail.show()
    sys.exit(app.exec_())

